### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cxsu** [cxsu/swage#1]
- [x] Support OAS JSON format (by `go-openapi/spec`)
- [x] Support OAS YAML format (by `go-openapi/spec`)
- [x] Support data from web server (by `go-openapi/spec`)
- [x] Improve code coverage
- [x] Support OAS [v2.0](http://spec.openapis.org/oas/v2.0)
- [ ] Support OAS [v3.0 (latest)](http://spec.openapis.org/oas/v3.0.3) (by [go-openapi/spec3](https://github.com/go-openapi/spec3))
- [ ] Make more [templates](https://github.com/cxsu/swage/blob/main/docs/templates.md)
